version: '3.8'

services:
  pm-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:3000"
    environment:
      - NODE_ENV=production
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGDATABASE=${PGDATABASE}
      - DATABASE_URL=postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}

    restart: unless-stopped
